-- MySQL Script generated by MySQL Workbench
-- 05/08/19 03:33:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sivenp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sivenp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sivenp` DEFAULT CHARACTER SET utf8 ;
USE `sivenp` ;

-- -----------------------------------------------------
-- Table `sivenp`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`empresa` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(30) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`categorias` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_categorias_empresa1_idx` (`cod_empresa` ASC),
  CONSTRAINT `fk_categorias_empresa1`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `sivenp`.`empresa` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`produtos` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT UNSIGNED NOT NULL,
  `cod_categoria` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NULL,
  `quantidade` INT NULL,
  `valor_uni_custo` DOUBLE NULL,
  `valor_uni_venda` DOUBLE NULL,
  `valor_uni_receita` DOUBLE NULL,
  `valor_total_receita` DOUBLE NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_produtos_categorias1_idx` (`cod_categoria` ASC),
  INDEX `fk_produtos_empresa1_idx` (`cod_empresa` ASC),
  CONSTRAINT `fk_produtos_categorias1`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `sivenp`.`categorias` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_empresa1`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `sivenp`.`empresa` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`clientes` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(25) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(120) NULL,
  `rua` VARCHAR(100) NULL,
  `numero` VARCHAR(20) NULL,
  `bairro` VARCHAR(45) NULL,
  `complemento` VARCHAR(255) NULL,
  `cidade` VARCHAR(30) NULL,
  `estado` VARCHAR(20) NULL,
  `cep` VARCHAR(45) NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_clientes_empresa1_idx` (`cod_empresa` ASC),
  CONSTRAINT `fk_clientes_empresa1`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `sivenp`.`empresa` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`vendas` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT UNSIGNED NOT NULL,
  `cod_cliente` INT UNSIGNED NOT NULL,
  `valor_total` DOUBLE NULL,
  `desconto` INT NULL,
  `valor_final` DOUBLE NULL,
  `valor_pago` DOUBLE NULL,
  `valor_restante` DOUBLE NULL,
  `status` VARCHAR(45) NULL,
  `data` DATE NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_vendas_clientes1_idx` (`cod_cliente` ASC),
  INDEX `fk_vendas_empresa1_idx` (`cod_empresa` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `sivenp`.`clientes` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_empresa1`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `sivenp`.`empresa` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`listar_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`listar_vendas` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_venda` INT UNSIGNED NOT NULL,
  `cod_produto` INT UNSIGNED NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_uni_venda` DOUBLE NULL,
  `valor_total` DOUBLE NULL,
  `data` DATE NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_listar_vendas_vendas1_idx` (`cod_venda` ASC),
  INDEX `fk_listar_vendas_produtos1_idx` (`cod_produto` ASC),
  CONSTRAINT `fk_listar_vendas_vendas1`
    FOREIGN KEY (`cod_venda`)
    REFERENCES `sivenp`.`vendas` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listar_vendas_produtos1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `sivenp`.`produtos` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`historico_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`historico_pagamento` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_venda` INT UNSIGNED NOT NULL,
  `valor` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_historico_pagamento_vendas1_idx` (`cod_venda` ASC),
  CONSTRAINT `fk_historico_pagamento_vendas1`
    FOREIGN KEY (`cod_venda`)
    REFERENCES `sivenp`.`vendas` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sivenp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sivenp`.`usuario` (
  `cod` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `nivel_acesso` INT NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `status` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`cod`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuario_empresa_idx` (`cod_empresa` ASC),
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `sivenp`.`empresa` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
