-- LISTAR TODOS OS USUÁRIOS --
SELECT * FROM usuario;

-- LISTAR TODOS USUÁRIO DA EMPRESA COD 1 --
SELECT * FROM usuario WHERE cod_empresa='1';

-- LISTAR TODOS USUÁRIOS DA EMRESA COD 1 QUE TEM NÍVEL DE ACESSO MAIOR QUE 1
SELECT * FROM usuario WHERE cod_empresa='1' AND nivel_acesso>'1';

-- LISTAR TODOS USUÁRIOS COM STATUS 1 [ATIVO]
SELECT * FROM usuario WHERE status='1;'

-- LISTAR TODOS USUÁRIOS COM COD 2 
SELECT * FROM usuario WHERE cod='2';

